apiVersion: v1
kind: Service
metadata:
  name: streaming
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: streaming
  name: streaming
spec:
  sessionAffinity: ClientIP
  selector:
    app: streaming
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer