apiVersion: v1
kind: Service
metadata:
  name: streaming
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  sessionAffinity: ClientIP
  selector:
    app: streaming
  ports:
    - port: 6000
      targetPort: 6000
  type: LoadBalancer